### PR TITLE
Fixes

### LINKED ISSUE #232: [PE-D] Invalid commands containing valid keywords treated as valid command
When in the calendar view mode, commands such as "next back back" or "month year day" are treated as valid "next" and "month" commands respectively. Perhaps an error could be raised instead?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: pattan9955/ped#1

### LINKED ISSUE #235: [PE-D] Typo in UG
"bellow" -> "below"

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: ganhongyao/ped#2

### LINKED ISSUE #236: [PE-D] Lesson clash does not appear to be listed in UG
This clashes with an existing lesson but I can't seem to find documentation on this in the UG; might make sense to add a note or a warning to the user there and/or in the application.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: lwlshawn/ped#2

### LINKED ISSUE #239: [PE-D] Example command under `edit` does not work
-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ganhongyao/ped#4

### LINKED ISSUE #243: [PE-D] Time constraints on lesson times
Lesson times before 8am or after 10pm are not allowed. However, some tutors may have night lessons that extend past 10pm or morning lessons that start before 8am. Perhaps this restraint could be removed?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: pattan9955/ped#5

### LINKED ISSUE #244: [PE-D] Unsure of the F2 shortcut functionality
According to the UG, F2 is a shortcut for list, but it looks like it is more of a shortcut for swapping to the current list of students.

Steps I took:
1. Use a find command to filter the list to 1 student "find n/Roy"
2. Press F2.
3. The list still only contains Roy instead of the full list that would be seen with the list command.

This might just be a minor documentation issue, but I really like the shortcuts feature.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: beefham/ped#1

### LINKED ISSUE #245: [PE-D] "find" command does not work for partial matching with tags
Steps to reproduce
1. open app with sample data (should have students tagged with "zoom")
2. execute command `t/zo`

Expected behaviour
- students with tags "zoom" should be matched, since it's mentioned in UG that keywords can match partially

Actual behaviour
- no match

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ganhongyao/ped#5

### LINKED ISSUE #270: [PE-D] MacOS cmd+Q screen
Maximise in macOS, then use cmd+Q (for quitting application), the following screen shows (subsequent cmd+Q will render the screen black, but the app still runs and you can't quit it anymore):

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: zhenghanlee/ped#7

### LINKED ISSUE #273: [PE-D] Time constraint for lessons not documented in UG
The constraint that a lesson must be conducted between 0800-2200 is not found in the UG.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: ganhongyao/ped#12

### LINKED ISSUE #283: UI BUG: Selected Person does not show lessons

### PR DESCRIPTION
**Pull request by Chesterwongz**
1. closes #245 
   - removed mention about partial matching since the table already suggests the expected outcome
 2. closes #244 
   - removed mention about `F2` shortcut in `list` command
 3. closes #243 and closes #273 
   - Add mention of feature to UG, and add future plans to toggle it.
 4. closes #239 
   - Remove f/0 from `edit`
  5. closes #236 
    - Add mention in UG
  6. closes #235 
  7. closes #232 
    - make chaining commands invalid
  8. closes #283 
    - clear selection whenever list is shown
    - Add listener for mouseclicks ~!!NOTE THIS CAUSES THE LESSON PANEL TO BOUNCE A LOT!!~ fixed by #227 
  9. closes #270 
    - Added a check to ensure listener does not capture ctrl/shift keys

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddressBookParser.java [hunk 1]
```diff
@@ -80,66 +80,78 @@ public Command parseCommand(String userInput) throws ParseException {
...
             return new ViewCommandParser().parse(arguments);
 
-        case ListCommand.COMMAND_WORD:
-            return new ListCommand();
+        case PaidCommand.COMMAND_WORD:
+            return new PaidCommandParser().parse(arguments);
 
-        case CalendarCommand.COMMAND_WORD:
-            return new CalendarCommand();
+        default:
```
Comment (Xiaoyunnn) [inline src/main/java/seedu/address/logic/parser/AddressBookParser.java:92]: this branch is very long, can create another method here?

File: docs/UserGuide.md [hunk 2]
```diff
@@ -128,9 +128,12 @@ This section describes the available features in TAB.
 * If a parameter is expected only once in the command, but you specified it multiple times, only the last occurrence of the parameter will be taken.<br>
   e.g. if you specify `p/12341234 p/56785678`, only `p/56785678` will be taken.
 
-* Extraneous parameters for commands that do not take in parameters (such as `help`, `list`, `exit` and `clear`) will be ignored.<br>
+* Extraneous parameters for commands that do not take in parameters (such as `help`, `list`, `calendar`, `exit`, `clear` etc.) will be ignored.<br>
   e.g. if the command specifies `help 123`, it will be interpreted as `help`.
```
Comment (Xiaoyunnn) [inline docs/UserGuide.md:132]: image

image
both `help 123` and `remind 123` are invalid commands and returns the same result showing valid command for help, same for other single word commands

File: docs/UserGuide.md [hunk 3]
```diff
@@ -568,9 +569,9 @@ the fees of these lessons will not be deducted for you. Same for shifting start
 
 <div style="page-break-after: always;"></div>
 
-### Viewing your Calendar
+### Managing Your Schedule
 
-This section guides you on how to use TAB's calendar interface. Typing any of the commands in this section will bring you to the calendar interface. Any other command, such as `list` or `tag`, will bring you right out.
+This section guides you on how to use TAB's calendar interface. Typing any of the commands in this section will bring you to the calendar interface. Any command from other sections, such as `list` or `tag`, will bring you right out.
```
Comment (Xiaoyunnn) [inline docs/UserGuide.md:574]:
```suggestion
This section guides you on how to use TAB's calendar interface. Typing any of the commands in this section will bring you to the calendar interface. Any command from other sections, such as `list` or `tags`, will bring you right out.
```

File: docs/UserGuide.md (hunk 2 above)
Comment (Xiaoyunnn) [inline docs/UserGuide.md:132]: extra params will render the command invalid instead of being ignored..?

File: docs/UserGuide.md [hunk 4]
```diff
@@ -128,9 +128,12 @@ This section describes the available features in TAB.
...
   e.g. if you specify `p/12341234 p/56785678`, only `p/56785678` will be taken.
 
-* Extraneous parameters for commands that do not take in parameters (such as `help`, `list`, `exit` and `clear`) will be ignored.<br>
-  e.g. if the command specifies `help 123`, it will be interpreted as `help`.
-  
+* Extraneous parameters for commands that do not take in parameters (such as `help`, `list`, `calendar`, `exit`, `clear` etc.) are not valid.<br>
+  e.g. `help 123` is not a valid command.
+
+* Chaining commands is not supported.<br>
+  e.g. A chain of commands such as `next next back next` or `list calendar day` are not a valid commands.
```
Comment (Xiaoyunnn) [inline docs/UserGuide.md:135]:
```suggestion
  e.g. A chain of commands such as `next next back next` or `list calendar day` is an invalid command.
```
```suggestion
  e.g. A chain of commands such as `next next back next` or `list calendar day` are not a valid commands.
```

File: docs/UserGuide.md [hunk 5]
```diff
@@ -371,6 +365,15 @@ Optional fields for a **recurring** lesson is:
 * End date
 * Cancelled dates
 
+TAB has features to help to prevent scheduling mistakes.
+For example, we help you avoid mistakes scheduling two lessons at the same slots by ensuring that lessons never overlap.
+Additionally, we help to avoid accidentally scheduling lessons outside working hours.
```
Comment (Xiaoyunnn) [inline docs/UserGuide.md:370]:
```suggestion
Additionally, we help to avoid accidentally scheduling lessons outside working hours (before 0800 and after 2200 hours).
```

File: docs/UserGuide.md [hunk 6]
```diff
@@ -316,16 +316,10 @@ Notes about search keywords:
 
 * You must provide at least one keyword to search for.<br>
   e.g. entering just `find n/` alone is not a valid command as the keyword is empty.
-
-* Tags must only have one keyword.<br>
-  e.g. `find t/zoom math` is invalid. To search by multiple tags, you can do `find t/zoom t/math`.
```
Comment (lingshanng) [inline docs/UserGuide.md:321]: I'll probably reformat find to explain the cases more clearly. Can you revert this first, I'll change on my side, thanks.

File: docs/UserGuide.md [hunk 7]
```diff
@@ -316,16 +316,10 @@ Notes about search keywords:
...
   
 * The search is case-insensitive.<br>
   e.g. keyword `hans` will match `Hans`.
 
-* A keyword can match a word partially.<br>
-  e.g. keyword `math` will match `mathematics`.
```
Comment (lingshanng) [inline docs/UserGuide.md:327]: I don't think removing solves it as it's not addressed in table? I'll think about how better to represent this.

File: docs/UserGuide.md [hunk 8]
```diff
@@ -785,13 +783,13 @@ Action | Format, Examples
...
-**View Schedule of Year** | `year`
-**Navigate forward in Schedule** | `next`
-**Navigate backward in Schedule** | `back`
+**View Daily Calendar** | `day`
+**View Weekly Calendar** | `week`
+**View Monthly Calendar** | `month`
+**View Yearly Calendar** | `year`
+**Navigate to Today** | `today`
+**Navigate forward in Calendar** | `next`
+**Navigate backward in Calendar** | `back`
```
Comment (lingshanng) [inline docs/UserGuide.md:792]: update in Help window as well?

File: src/main/java/seedu/address/ui/SchedulePanel.java [hunk 9]
```diff
@@ -79,14 +87,20 @@ private void initialiseDayPage() {
...
         calendarView.getWeekPage().getDetailedWeekView().setHoursLayoutStrategy(FIXED_HOUR_COUNT);
         calendarView.getWeekPage().getDetailedWeekView().setEarlyLateHoursStrategy(SHOW_COMPRESSED);
     }
 
+    /**
+     * Sets up the calendarView's YearPage.
+     */
     private void initialiseYearPage() {
-        calendarView.getYearPage().getMonthSheetView().setShowWeekNumber(false);
+        calendarView.getYearPage().getMonthSheetView().setShowWeekNumber(false); // This doesn't seem to work
```
Comment (angkoonhwee) [inline src/main/java/seedu/address/ui/SchedulePanel.java:103]: What do you mean? Then why not remove it?

File: docs/UserGuide.md [hunk 10]
```diff
@@ -371,6 +365,15 @@ Optional fields for a **recurring** lesson is:
...
 * Cancelled dates
 
+TAB has features to help to prevent scheduling mistakes.
+For example, we help you avoid mistakes scheduling two lessons at the same slots by ensuring that lessons never overlap.
+Additionally, we help to avoid accidentally scheduling lessons outside working hours.
+
+In the future, we intend to add some nice-to-have features that will allow you to customise your working hours,
+as well as specify minimum/maximum lesson durations so that accidents like mistyping a 10-minute lesson won't happen.
+Additionally, we will allow you to toggle these checks on and off, just in case you don't want them.
+Do look forward to these features!
```
Comment (angkoonhwee) [inline docs/UserGuide.md:375]: I don't quite understand these additional future features and is there a need to mention these? >.<

Comment (eeliana) [reply docs/UserGuide.md:375]: I think these are to mitigate the feature flaws claims as upcoming features

File: docs/UserGuide.md [hunk 11]
```diff
@@ -371,6 +371,15 @@ Optional fields for a **recurring** lesson is:
 * End date
 * Cancelled dates
 
+TAB has features to help to prevent scheduling mistakes.
+For example, we help you avoid mistakes scheduling two lessons at the same slots by ensuring that lessons never overlap.
```
Comment (lingshanng) [inline docs/UserGuide.md:375]:
```suggestion
For example, we help you avoid mistakes such as scheduling two lessons at the same slots by ensuring that lessons never overlap.
```

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 12]
```diff
@@ -4,11 +4,11 @@
  * Container for user visible messages.
  */
 public class Messages {
-
-    public static final String MESSAGE_UNKNOWN_COMMAND = "Unknown command";
+    public static final String MESSAGE_HELP_TIP = "💡 TIP: Type \"help\" to view the valid commands!";
+    public static final String MESSAGE_UNKNOWN_COMMAND = "Unknown command" + "\n" + MESSAGE_HELP_TIP;
```
Comment (lingshanng) [inline src/main/java/seedu/address/commons/core/Messages.java:8]:
```suggestion
    public static final String MESSAGE_UNKNOWN_COMMAND = "Unknown command!" + "\n" + MESSAGE_HELP_TIP;
```

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 13]
```diff
@@ -314,6 +318,14 @@ private void handlePersonGridPanel(Person student) {
         centerPanel.displayPersonGridPanel(student, logic.getLessonList(student));
     }
 
+    private void handleStudents(CommandResult commandResult) {
```
Comment (lingshanng) [inline src/main/java/seedu/address/ui/MainWindow.java:321]: add javadoc

**Review by lingshanng — APPROVED** [review]
LGTM
